import NavBar from "@/app/components/navigation/NavBar"
import './globals.css'
import { MyNextAuthProvider } from "./components/auth/MyNextAuthProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout(
  { children, }: { children: React.ReactNode }
) {
  return (
    <html lang="en">
      <body>
        <MyNextAuthProvider>
          <header>
            <NavBar />
          </header>
          <div>
            {children}
          </div>
        </MyNextAuthProvider>
      </body>
    </html>
  )
}
