import './globals.css'
import SessionProvider from "./components/auth/SessionProvider"
import { getServerSession } from "next-auth"
import TopNavigationBar from "@/app/components/navigation/TopNavigationBar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout(
  { children, }: { children: React.ReactNode }) {
  const session = await getServerSession();


  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <header>
            <TopNavigationBar />
          </header>
          <main>
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
